# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

departmentCode: "1"

alpha:
  version: 6.5.1
  values:
    h2c:
      enabled: true
bravo:
  version: 6.5.1
  values:
    h2c:
      enabled: true
charlie:
  version: 6.5.1
  enabled: false
  values:
    h2c:
      enabled: true
keda:
  version: 0.1.1
  resources:
    operator:
      limits:
        cpu: 100m
